pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: 'Get NonProd Configuration Files'
  inputs:
    targetType: 'inline'
    script: |
       cd config/nonprod
       $config=ls *.json
       Write-Host "##vso[task.setvariable variable=nonprod-config]$config"
       Write-Host $config
- task: PowerShell@2
  displayName: 'Get Prod Configuration Files'
  inputs:
    targetType: 'inline'
    script: |
       cd config/prod
       $config=ls *.json
       Write-Host "##vso[task.setvariable variable=nonprod-config]$config"
       Write-Host $config
- template: build/deploy.yml
  parameters:
    param: ["filaname1","filaname2","filaname3"]
