pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'windows-latest'
steps:     
- task: TerraformInstaller@0
  displayName: Terraform install
  inputs:
    terraformVersion: $(terraformVersion)

- task: TerraformCLI@0
  displayName: Terraform initialize
  inputs:
    command: init
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform
    backendType: azurerm
    ensurebackend: true
    backendServiceArm: $(serviceConnection)
    backendAzureRmResourceGroupName: $(rg)
    backendAzureRmResourceGroupLocation: $(location)
    backendAzureRmStorageAccountName: $(storage_account)
    backendAzureRmStorageAccountSku: Standard_LRS
    backendAzureRmContainerName: tfstate
    backendAzureRmKey: rdo-sendgrid/$(environment).tfstate

- task: TerraformCLI@0
  displayName: Terraform validate
  inputs:
    command: validate
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform/

- task: TerraformCLI@0
  displayName: Terraform plan
  inputs:
    command: plan
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
    environmentServiceName: $(serviceConnection)

- task: TerraformCLI@0
  displayName: Terraform apply
  inputs:
    command: apply
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform/environment/
    environmentServiceName: $(serviceConnection)
    commandOptions: --auto-approve