pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: 'Read NonProd Configuration'
  inputs:
    targetType: 'inline'
    script: |
       Write-Host "Fetching config files"
       cd config/nonprod
       $a=git ls-files
       foreach ($i in $a) {
          Write-Host "##vso[task.setvariable variable=filename]$i"
          Write-Host "printing"$i
       }  
- template: build/deploy.yml
  parameters:
    param: ["filaname1","filaname2","filaname3"]
