pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'vs2017-win2016'
steps:
- task: PowerShell@2
  displayName: 'Install PowerShell AZ'
  inputs:
    targetType: inline
    script: |
      Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force -AcceptLicense
- task: PowerShell@2
  displayName: 'Apply NonProd Configuration'
  inputs:
    targetType: 'inline'
    script: |
      $env = 'non-prod'
      cd $SourcesDirectory/config/$env
      $config=ls *.json
      Foreach ($i in $config)
      {
        echo 'loop'
        New-AzResourceGroup -Name $i-$env -Location UKSouth
        New-AzResourceGroupDeployment -ResourceGroupName $i-$env `-TemplateFile arm/template.json 
      }
- task: PowerShell@2
  displayName: 'Apply Prod Configuration'
  inputs:
    targetType: 'inline'
    script: |
      $env = 'prod'
      cd config/$env
      $config=ls *.json
      Foreach ($i in $config)
      {
        echo 'loop'
        New-AzResourceGroup -Name $i-$env -Location UKSouth
        New-AzResourceGroupDeployment -ResourceGroupName $i-$env `-TemplateFile arm/template.json 
      }
