pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'windows-latest'
steps:
- task: AzurePowerShell@4
  displayName: 'Apply NonProd Configuration'
  inputs:
    ConnectedServiceNameARM: 'DCD-CNP-DEV'
    targetType: 'inline'
    workingDirectory: $(Build.SourcesDirectory)
    azurePowerShellVersion: 'latestVersion'
    script: |
      Write-Host 'hello'
- task: AzurePowerShell@4
  displayName: 'Apply Prod Configuration'
  inputs:
    targetType: 'inline'
    workingDirectory: $(Build.SourcesDirectory)
    azurePowerShellVersion: latestVersion
    script: |
      $env = 'prod'
      cd config\$env
      $config = Get-ChildItem
      Write-Host $config
      Foreach ($i in $config)
      {
        New-AzResourceGroup -Name $i-$env -Location UKSouth
        New-AzResourceGroupDeployment -ResourceGroupName $i-$env -TemplateFile arm\template.json 
      }
