pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'windows-latest'
steps:
- task: CopyFiles@2
  displayName: Copy provisioning scripts
  inputs:
    SourceFolder: config/nonprod
    TargetFolder: '$(build.artifactstagingdirectory)/sendgrid-nonprod'
- task: PublishBuildArtifacts@1
  displayName: Publish infrastructure artifacts
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/sendgrid-nonprod'
    ArtifactName: sendgrid-nonprod
- task: AzureCLI@2
  displayName: 'Apply NonProd Configuration'
  inputs:
    azureSubscription: 'DCD-CNP-DEV'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    script: |
      Write-Host "Azure Auth"
      Select-AzSubscription -SubscriptionId $subscriptionId
      $env = 'nonprod'
      $config = Get-ChildItem -Path config\$env\*.json
      Foreach ($i in $config)
      {
        Write-Host $i
        New-AzResourceGroup -Name $i-$env -Location UKSouth
        New-AzResourceGroupDeployment -ResourceGroupName $i-$env -TemplateFile arm\template.json 
      }
