pr:
- Integration

pool:
  name: Azure Pipelines
  demands: azureps
  vmImage: 'vs2017-win2016'

steps:
- task: CmdLine@2
  displayName: 'Read NonProd Configuration'
  inputs:
    script: |
        FOR /F "delims=|" %%I IN ('DIR "$(Build.SourcesDirectory)\config\nonprod*.json*" /B /O:D') DO SET NewestFile=%%I
        echo "##vso[task.setvariable variable=NewFileName]NewestFile"
- template: build/deploy.yml
 parameters:
   param: ["filaname1","filaname2","filaname3"]
